# Comment
name: Fetch Secrets from Conjur

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch-secrets:
    runs-on: [self-hosted]  # Specify your self-hosted runner label and OS
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: cyberark/conjur-action@v2.0.5
        with:
          url: https://shimcity.secretsmgr.cyberark.cloud/api
          account: conjur
          authn_id: github-jwt-shimran-production
          secrets: |
            "data/vault/Shimran-Github-Conjur/Operating System-UnixSSH-CONJUREX-Mygithubdbusername/password"|CONJUR_PASS;"data/vault/Shimran-Github-Conjur/Operating System-UnixSSH-CONJUREX-Mygithubdbusername/username"|CONJUR_USERNAME;
      
      - run: |
          echo $CONJUR_PASS
