# Runner hosted on cphost  run bash actions-runner/run.sh

name: Fetch Secrets from Conjur

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch-secrets:
    runs-on: [self-hosted]  # Specify your self-hosted runner label and OS
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: cyberark/conjur-action@v2.0.5
        with:
          url: https://shimcity.secretsmgr.cyberark.cloud/api
          account: conjur
          authn_id: github-jwt-shimran-production
          secrets: |
            data/vault/Shimran-Github-Conjur/Database-MySQL-mysqladdress-test/password|CONJUR_PASS;data/vault/Shimran-Github-Conjur/Database-MySQL-mysqladdress-test/username|CONJUR_USERNAME;
      
      - run: |
          echo $CONJUR_PASS | sed 's/./& /g'
          IDTOKEN=$(curl -H "Authorization: bearer  ${{steps.script.outputs.TOKEN}}" ${{steps.script.outputs.IDTOKENURL}}  -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json" -d "{}" | jq -r '.value')
          echo $IDTOKEN
          jwtd() {
            if [[ -x $(command -v jq) ]]; then
                jq -R 'split(".") | .[0],.[1] | @base64d | fromjson' <<< "${1}"
                echo "Signature: $(echo "${1}" | awk -F'.' '{print $3}')"
            fi
          }
          jwtd $IDTOKEN
          echo "idToken=${IDTOKEN}" >> $GITHUB_OUTPUT
        id: tokenid
